CineAvanzada/CineAvanzada/Controllers/MasVistasController.cs
using CineAvanzada.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CineAvanzada.Controllers
{
    public class MasVistasController : Controller
    {
        // GET: MasVistas
        public ActionResult MasVistas()
        {
            var masVstas = new MasVistasService();
            var model = masVstas.MasVendidas();
            return View(model);
        }
    }
}

CineAvanzada/CineAvanzada/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cinema Plus", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cartelera", "Cartelera", "Cartelera")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink(linkText: "Promociones", actionName: "Promociones",
                            controllerName: "Promociones", routeValues: new
                            {
                                idUsuario = User.Identity.GetUserId()
                            }, htmlAttributes: new { })
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Promociones", "Promociones", "Promociones")</li>
                    }
                    <li>@Html.ActionLink("Mas Vistas", "MasVistas", "MasVistas")</li>
					<li>@Html.ActionLink("Salas", "Salas", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>